spring.application.name=api-orcamento-manipulado
server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/api_farmacia?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
openai.api.key=${OPENAI_API_KEY}
openai.api.url=https://openai.com
spring.config.import=optional:file:.env[.properties]
