# Configurações de Produção no Render (PostgreSQL)
spring.jpa.hibernate.ddl-auto=update

# Captura as variáveis que configuraremos no painel do Render
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Garante que o banco use o fuso horário correto para auditoria de orçamentos
spring.jpa.properties.hibernate.jdbc.time_zone=America/Sao_Paulo

logging.level.org.hibernate.SQL=WARN


