# Configurações Globais da Aplicação
spring.application.name=api-orcamento-manipulado
server.port=8082

# Gerenciamento de Perfis (Se não houver variável no ambiente, roda o local por padrão)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# Configurações globais que a IA e o JWT precisam ler de forma transparente
gemini.api.key=${GEMINI_API_KEY:}
jwt.secret=${JWT_SECRET:}
